// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKMQGyVBMlqRXHgoPpn-435nZ4vcmIL9c',
    appId: '1:243542474887:web:da6f8ec167ad4120573822',
    messagingSenderId: '243542474887',
    projectId: 'todolist-fd3cc',
    authDomain: 'todolist-fd3cc.firebaseapp.com',
    storageBucket: 'todolist-fd3cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFU46njhBzHM40oWk7fTnzQY7byijv7OE',
    appId: '1:243542474887:android:d8edced03ae7abf2573822',
    messagingSenderId: '243542474887',
    projectId: 'todolist-fd3cc',
    storageBucket: 'todolist-fd3cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb7foGDi3FkAX2zxdWoVrWkLNOpoYwohc',
    appId: '1:243542474887:ios:a2d097c0f73e3bb0573822',
    messagingSenderId: '243542474887',
    projectId: 'todolist-fd3cc',
    storageBucket: 'todolist-fd3cc.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb7foGDi3FkAX2zxdWoVrWkLNOpoYwohc',
    appId: '1:243542474887:ios:a2d097c0f73e3bb0573822',
    messagingSenderId: '243542474887',
    projectId: 'todolist-fd3cc',
    storageBucket: 'todolist-fd3cc.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKMQGyVBMlqRXHgoPpn-435nZ4vcmIL9c',
    appId: '1:243542474887:web:113b42d07ed5a100573822',
    messagingSenderId: '243542474887',
    projectId: 'todolist-fd3cc',
    authDomain: 'todolist-fd3cc.firebaseapp.com',
    storageBucket: 'todolist-fd3cc.firebasestorage.app',
  );
}
